%% |cmocean| documentation 
% The |cmocean| function returns perceptually-uniform colormaps generated by Kristen Thyng. A 
% detailed description of the cmocean project is available at <http://matplotlib.org/cmocean>.
% 
%% Syntax 
% 
%  cmap = cmocean('ColormapName') 
%  cmap = cmocean('-ColormapName') 
%  cmap = cmocean(...,NLevels)
%  cmap = cmocean(...,'zero') 
%  cmocean(...)
% 
%% Description 
% 
% |cmap = cmocean('ColormapName')| returns a 256x3 colormap. |ColormapName| can be any of 
% of the following: 
% 
% <<cmocean.png>>
%
% |cmap = cmocean('-ColormapName')| a minus sign preceeding any |ColormapName| flips the
% order of the colormap. 
%
% |cmap = cmocean(...,NLevels)| specifies a number of levels in the colormap.  Default
% value is |256|. 
%
% |cmap = cmocean(...,'zero')| centers the colormap on zero using the current |caxis| limits. 
% This option is designed for use with divergent colormaps when the maximum value in 
% the |caxis| limits does not exactly equal the absolute value of the lower |caxis| limit.
%
% |cmocean(...)| without any outputs sets the current colormap.  
% 
%% Examples 
% Using this sample plot: 

imagesc(peaks(1000)+1)
colorbar

%%
% Set the colormap to |'algae'|: 
 
cmocean('algae') 
 
%%
% Same as above, but with an inverted |algae| colormap: 
 
cmocean('-algae')

%%
% Set the colormap to a 12-level |'solar'|: 
 
cmocean('solar',12)

%%
% Get the RGB values of a 5-level thermal colormap: 

RGB = cmocean('thermal',5)

%%
% Some of those values are below zero and others are above. If this dataset represents
% anomalies, perhaps a diverging colormap is more appropriate: 

cmocean('balance') 

%%
% It's unlikely that 1.7776 is an interesting value about which the data values 
% diverge.  If you want to center the colormap on zero using the current color 
% axis limits, simply include the |'zero'| tag:  

cmocean('balance','zero') 

%% Author Info 
% This function was written by <http://www.chadagree.com Chad A. Greene> of the Institute for Geophysics at the 
% University of Texas at Austin (UTIG), June 2016, using colormaps created by <http://kristenthyng.com/ Kristen
% Thyng> of Texas A&M University, Department of Oceanography. More information on the
% cmocean project can be found at <http://matplotlib.org/cmocean>. 